server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1之间，1则表示全部采集
    probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///cloud2022?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123
    druid:
      test-while-idle: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jkx.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #     单机版
      defaultZone: http://localhost:7001/eureka
#        defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    #    配置自定义服务名和显示真实ip地址
    instance-id: payment8001
    prefer-ip-address: true
##    发送心跳间隔时间
#    lease-renewal-interval-in-seconds: 1
##    服务端等待新一次心跳时间，超时视为服务作废，剔除服务
#    lease-expiration-duration-in-seconds: 2



