server:
  port: 7001

#单机版
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

eureka:
  instance:
    #eureka服务端的实例名字
    hostname: eureka7001
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      #      集群版
      #      defaultZone: http://eureka7002:7002/eureka/
      #     单机
      defaultZone: http://eureka7001:7001/eureka/
#  server:
#    #    关闭自我保护机制，保证不可用服务被及时踢除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
