server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: hystrix-payment8001
    prefer-ip-address: true


